name: 'APK Build'
description: 'Build apk package for applications'
author: 'Zack Siri'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
